### ISSUE TITLE
请问这个问题怎么解决

### ISSUE THREAD

**Issue by shenhuanting** [EASY233/Gather#1]
[*] 共搜索到结果:1906
[*] 请输入你需要的数量:1500
Traceback (most recent call last):
  File "C:\Gather-master (1)\Gather-master\Gather.py", line 9, in <module>
    cmdline()
  File "C:\Gather-master (1)\Gather-master\lib\cmdline.py", line 19, in cmdline
    options(args)
  File "C:\Gather-master (1)\Gather-master\lib\cmdline.py", line 27, in options
    Shodan()
  File "C:\Gather-master (1)\Gather-master\api\data_from_shodan.py", line 25, in __init__
    if 'matches' in context:
UnboundLocalError: local variable 'context' referenced before assignment

**Comment by shenhuanting** [comment]
Why can't I extract the full quantity of Shodan

**Comment by EASY233** [comment]
你好，这个项目已不再维护，建议使用更加优秀的工具，非常抱歉

**Comment by shenhuanting** [comment]
请问更加优秀的工具是哪个？有链接吗？

**Comment by EASY233** [comment]
我个人也在使用这个https://github.com/wgpsec/fofa_viewer
